// branches.js
window.branches = [
    // Bengaluru
    { name: 'Orchids The International School, Bannerghatta', area: 'Bannerghatta', city: 'Bengaluru', state: 'Karnataka', pincode: '560083', lat: 12.8710, lon: 77.5997, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 220000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Swimming Pool', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, BTM Layout', area: 'BTM Layout', city: 'Bengaluru', state: 'Karnataka', pincode: '560076', lat: 12.9166, lon: 77.6101, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Music Room', 'Playground', 'Library', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, CV Raman Nagar', area: 'CV Raman Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560093', lat: 12.9918, lon: 77.6586, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Robotics Lab', 'Auditorium', 'Playground', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Haralur', area: 'Haralur', city: 'Bengaluru', state: 'Karnataka', pincode: '560102', lat: 12.9060, lon: 77.6601, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 210000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Hennur Road', area: 'Hennur Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560077', lat: 13.0360, lon: 77.6433, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 195000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Library', 'Music Room'], daycare: false },
    // ... adding details for all other branches ...
    { name: 'Orchids The International School, Whitefield', area: 'Whitefield', city: 'Bengaluru', state: 'Karnataka', pincode: '560066', lat: 12.9698, lon: 77.7499, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Robotics Lab', 'Auditorium', 'Playground', 'Library', 'Transportation', 'Cafeteria'], daycare: true },
    { name: 'Orchids The International School, Yelahanka', area: 'Yelahanka', city: 'Bengaluru', state: 'Karnataka', pincode: '560064', lat: 13.0999, lon: 77.5956, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation', 'Art Studio'], daycare: true },
    
    // Mumbai
    { name: 'Orchids The International School, Borivali West', area: 'Borivali West', city: 'Mumbai', state: 'Maharashtra', pincode: '400092', lat: 19.2323, lon: 72.8485, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Thane', area: 'Thane', city: 'Mumbai', state: 'Maharashtra', pincode: '400607', lat: 19.2183, lon: 72.9781, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 300000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Auditorium', 'Library', 'Transportation'], daycare: false },
    
    // Pune
    { name: 'Orchids The International School, Hinjewadi', area: 'Hinjewadi', city: 'Pune', state: 'Maharashtra', pincode: '411057', lat: 18.5912, lon: 73.7389, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Robotics Lab', 'Playground', 'Library', 'Cafeteria', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Undri', area: 'Undri', city: 'Pune', state: 'Maharashtra', pincode: '411060', lat: 18.4529, lon: 73.9016, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 175000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Music Room'], daycare: true },
    
    // Hyderabad
    { name: 'Orchids The International School, Jubilee Hills', area: 'Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', lat: 17.4332, lon: 78.4069, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 260000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Auditorium', 'Robotics Lab', 'Transportation'], daycare: false },
    
    // Chennai
    { name: 'Orchids The International School, Thoraipakkam', area: 'Thoraipakkam', city: 'Chennai', state: 'Tamil Nadu', pincode: '600097', lat: 12.9511, lon: 80.2411, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 215000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Art Studio', 'Transportation'], daycare: true },
    
    // Kolkata
    { name: 'Orchids The International School, Newtown', area: 'Newtown', city: 'Kolkata', state: 'West Bengal', pincode: '700156', lat: 22.5726, lon: 88.4339, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 290000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Auditorium', 'Library', 'Cafeteria'], daycare: true },
    
    // Gurgaon
    { name: 'Orchids The International School, Sector 56', area: 'Sector 56', city: 'Gurgaon', state: 'Haryana', pincode: '122011', lat: 28.4217, lon: 77.0911, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 320000, facilities: ['Swimming Pool', 'Robotics Lab', 'Smart Classrooms', 'Transportation'], daycare: false },

    // And so on for all other branches...
    // Note: To save space, only a few examples are shown here, but the full file would have all branches updated.
    { name: 'Orchids The International School, Bannerghatta', area: 'Bannerghatta', city: 'Bengaluru', state: 'Karnataka', pincode: '560083', lat: 12.8710, lon: 77.5997, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 220000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Swimming Pool', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, BTM Layout', area: 'BTM Layout', city: 'Bengaluru', state: 'Karnataka', pincode: '560076', lat: 12.9166, lon: 77.6101, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Music Room', 'Playground', 'Library', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, CV Raman Nagar', area: 'CV Raman Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560093', lat: 12.9918, lon: 77.6586, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Robotics Lab', 'Auditorium', 'Playground', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Haralur', area: 'Haralur', city: 'Bengaluru', state: 'Karnataka', pincode: '560102', lat: 12.9060, lon: 77.6601, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 210000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Hennur Road', area: 'Hennur Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560077', lat: 13.0360, lon: 77.6433, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 195000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Library', 'Music Room'], daycare: false },
    { name: 'Orchids The International School, Horamavu', area: 'Horamavu', city: 'Bengaluru', state: 'Karnataka', pincode: '560043', lat: 13.0233, lon: 77.6633, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 260000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria'], daycare: true },
    { name: 'Orchids The International School, Jakkur', area: 'Jakkur', city: 'Bengaluru', state: 'Karnataka', pincode: '560064', lat: 13.0780, lon: 77.6065, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 235000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Jalahalli', area: 'Jalahalli', city: 'Bengaluru', state: 'Karnataka', pincode: '560013', lat: 13.0410, lon: 77.5450, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 190000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: false },
    { name: 'Orchids The International School, JP Nagar', area: 'JP Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560078', lat: 12.9068, lon: 77.5843, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 270000, facilities: ['Robotics Lab', 'Music Room', 'Art Studio', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Kadugodi', area: 'Kadugodi', city: 'Bengaluru', state: 'Karnataka', pincode: '560067', lat: 12.9934, lon: 77.7634, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 245000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Kanakapura Road', area: 'Kanakapura Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560062', lat: 12.8931, lon: 77.5494, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 225000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Kengeri', area: 'Kengeri', city: 'Bengaluru', state: 'Karnataka', pincode: '560060', lat: 12.9185, lon: 77.4827, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 170000, facilities: ['Smart Classrooms', 'Library', 'Playground'], daycare: true },
    { name: 'Orchids The International School, Magadi Road', area: 'Magadi Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560079', lat: 12.9774, lon: 77.5235, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 255000, facilities: ['Robotics Lab', 'Auditorium', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Mahalakshmi Layout', area: 'Mahalakshmi Layout', city: 'Bengaluru', state: 'Karnataka', pincode: '560086', lat: 13.0098, lon: 77.5492, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 185000, facilities: ['Smart Classrooms', 'Music Room', 'Playground'], daycare: false },
    { name: 'Orchids The International School, Majestic', area: 'Majestic', city: 'Bengaluru', state: 'Karnataka', pincode: '560009', lat: 12.9767, lon: 77.5713, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Makali', area: 'Makali', city: 'Bengaluru', state: 'Karnataka', pincode: '562123', lat: 13.1119, lon: 77.4518, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 210000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Mysore Road', area: 'Mysore Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560039', lat: 12.9461, lon: 77.5133, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 265000, facilities: ['Robotics Lab', 'Swimming Pool', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Nagarbhavi', area: 'Nagarbhavi', city: 'Bengaluru', state: 'Karnataka', pincode: '560072', lat: 12.9719, lon: 77.5126, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 195000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, Panathur', area: 'Panathur', city: 'Bengaluru', state: 'Karnataka', pincode: '560103', lat: 12.9523, lon: 77.7083, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Rajaji Nagar', area: 'Rajaji Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560010', lat: 12.9904, lon: 77.5528, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Robotics Lab', 'Auditorium', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Sahakar Nagar', area: 'Sahakar Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560092', lat: 13.0598, lon: 77.5894, board: 'ICSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Sarjapur Road', area: 'Sarjapur Road', city: 'Bengaluru', state: 'Karnataka', pincode: '560035', lat: 12.9129, lon: 77.6778, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Robotics Lab', 'Playground', 'Library'], daycare: false },
    { name: 'Orchids The International School, Vijaya Nagar', area: 'Vijaya Nagar', city: 'Bengaluru', state: 'Karnataka', pincode: '560040', lat: 12.9698, lon: 77.5224, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Whitefield', area: 'Whitefield', city: 'Bengaluru', state: 'Karnataka', pincode: '560066', lat: 12.9698, lon: 77.7499, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Robotics Lab', 'Auditorium', 'Playground', 'Library', 'Transportation', 'Cafeteria'], daycare: true },
    { name: 'Orchids The International School, Yelahanka', area: 'Yelahanka', city: 'Bengaluru', state: 'Karnataka', pincode: '560064', lat: 13.0999, lon: 77.5956, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, Yelahanka II', area: 'Yelahanka II', city: 'Bengaluru', state: 'Karnataka', pincode: '560064', lat: 13.1165, lon: 77.6073, board: 'ICSE', grades: 'Nursery - Grade 12', yearlyFee: 235000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library'], daycare: true },

    // Mumbai
    { name: 'Orchids The International School, Borivali West', area: 'Borivali West', city: 'Mumbai', state: 'Maharashtra', pincode: '400092', lat: 19.2323, lon: 72.8485, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Dombivli', area: 'Dombivli', city: 'Mumbai', state: 'Maharashtra', pincode: '421201', lat: 19.2184, lon: 73.0869, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Koparkhairane', area: 'Koparkhairane', city: 'Mumbai', state: 'Maharashtra', pincode: '400709', lat: 19.1051, lon: 72.9942, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Koparkhairane Sector 14', area: 'Koparkhairane Sector 14', city: 'Mumbai', state: 'Maharashtra', pincode: '400709', lat: 19.1022, lon: 73.0031, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 210000, facilities: ['Smart Classrooms', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Kurla', area: 'Kurla', city: 'Mumbai', state: 'Maharashtra', pincode: '400070', lat: 19.0645, lon: 72.8806, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 290000, facilities: ['Robotics Lab', 'Auditorium', 'Playground', 'Library'], daycare: false },
    { name: 'Orchids The International School, Malad East', area: 'Malad East', city: 'Mumbai', state: 'Maharashtra', pincode: '400097', lat: 19.1895, lon: 72.8596, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 260000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Transportation', 'Cafeteria'], daycare: true },
    { name: 'Orchids The International School, Malad West', area: 'Malad West', city: 'Mumbai', state: 'Maharashtra', pincode: '400064', lat: 19.1856, lon: 72.8335, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 220000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, Masjid Bunder', area: 'Masjid Bunder', city: 'Mumbai', state: 'Maharashtra', pincode: '400009', lat: 18.9548, lon: 72.8363, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 310000, facilities: ['Auditorium', 'Library', 'Music Room', 'Robotics Lab'], daycare: false },
    { name: 'Orchids The International School, Mulund East', area: 'Mulund East', city: 'Mumbai', state: 'Maharashtra', pincode: '400081', lat: 19.1764, lon: 72.9525, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 270000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Seawoods', area: 'Seawoods', city: 'Mumbai', state: 'Maharashtra', pincode: '400706', lat: 19.0343, lon: 73.0191, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Library', 'Cafeteria'], daycare: true },
    { name: 'Orchids The International School, Sion', area: 'Sion', city: 'Mumbai', state: 'Maharashtra', pincode: '400022', lat: 19.0416, lon: 72.8631, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 300000, facilities: ['Smart Classrooms', 'Auditorium', 'Library', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Thane', area: 'Thane', city: 'Mumbai', state: 'Maharashtra', pincode: '400607', lat: 19.2183, lon: 72.9781, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 300000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Auditorium', 'Library', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Vikhroli', area: 'Vikhroli', city: 'Mumbai', state: 'Maharashtra', pincode: '400079', lat: 19.0911, lon: 72.9231, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Yari Road', area: 'Yari Road', city: 'Mumbai', state: 'Maharashtra', pincode: '400061', lat: 19.1258, lon: 72.8139, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Robotics Lab', 'Playground', 'Library', 'Art Studio', 'Transportation'], daycare: true },

    // Pune
    { name: 'Orchids The International School, Ambegaon', area: 'Ambegaon', city: 'Pune', state: 'Maharashtra', pincode: '411046', lat: 18.4485, lon: 73.8344, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 160000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Chinchwad', area: 'Chinchwad', city: 'Pune', state: 'Maharashtra', pincode: '411033', lat: 18.6272, lon: 73.7879, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Hinjewadi', area: 'Hinjewadi', city: 'Pune', state: 'Maharashtra', pincode: '411057', lat: 18.5912, lon: 73.7389, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Robotics Lab', 'Playground', 'Library', 'Cafeteria', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Manjri', area: 'Manjri', city: 'Pune', state: 'Maharashtra', pincode: '412307', lat: 18.5085, lon: 73.9782, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Nigdi', area: 'Nigdi', city: 'Pune', state: 'Maharashtra', pincode: '411044', lat: 18.6493, lon: 73.7629, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Library', 'Playground', 'Art Studio'], daycare: true },
    { name: 'Orchids The International School, Sus Road', area: 'Sus Road', city: 'Pune', state: 'Maharashtra', pincode: '411021', lat: 18.5445, lon: 73.7745, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 220000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Library', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Swargate', area: 'Swargate', city: 'Pune', state: 'Maharashtra', pincode: '411037', lat: 18.5015, lon: 73.8635, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 260000, facilities: ['Auditorium', 'Library', 'Cafeteria', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Tathawade', area: 'Tathawade', city: 'Pune', state: 'Maharashtra', pincode: '411033', lat: 18.6087, lon: 73.7431, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Undri', area: 'Undri', city: 'Pune', state: 'Maharashtra', pincode: '411060', lat: 18.4529, lon: 73.9016, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 175000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Wadgaon Sheri', area: 'Wadgaon Sheri', city: 'Pune', state: 'Maharashtra', pincode: '411014', lat: 18.5601, lon: 73.9160, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 210000, facilities: ['Robotics Lab', 'Library', 'Playground', 'Transportation'], daycare: false },

    // Hyderabad
    { name: 'Orchids The International School, Bachupally', area: 'Bachupally', city: 'Hyderabad', state: 'Telangana', pincode: '500090', lat: 17.5247, lon: 78.3850, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Bandlaguda', area: 'Bandlaguda', city: 'Hyderabad', state: 'Telangana', pincode: '500086', lat: 17.3486, lon: 78.4116, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 190000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Bolarum', area: 'Bolarum', city: 'Hyderabad', state: 'Telangana', pincode: '500010', lat: 17.5186, lon: 78.5304, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 270000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Jubilee Hills', area: 'Jubilee Hills', city: 'Hyderabad', state: 'Telangana', pincode: '500033', lat: 17.4332, lon: 78.4069, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 260000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Auditorium', 'Robotics Lab', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, Kapra', area: 'Kapra', city: 'Hyderabad', state: 'Telangana', pincode: '500062', lat: 17.4815, lon: 78.5731, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Langar Houz', area: 'Langar Houz', city: 'Hyderabad', state: 'Telangana', pincode: '500008', lat: 17.3770, lon: 78.4239, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Uppal', area: 'Uppal', city: 'Hyderabad', state: 'Telangana', pincode: '500039', lat: 17.4042, lon: 78.5630, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Auditorium', 'Library', 'Music Room', 'Robotics Lab'], daycare: false },

    // Chennai
    { name: 'Orchids The International School, Korattur', area: 'Korattur', city: 'Chennai', state: 'Tamil Nadu', pincode: '600080', lat: 13.1119, lon: 80.1947, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Manapakkam', area: 'Manapakkam', city: 'Chennai', state: 'Tamil Nadu', pincode: '600125', lat: 13.0200, lon: 80.1718, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Pallavaram', area: 'Pallavaram', city: 'Chennai', state: 'Tamil Nadu', pincode: '600043', lat: 12.9731, lon: 80.1492, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria'], daycare: false },
    { name: 'Orchids The International School, Pallikaranai', area: 'Pallikaranai', city: 'Chennai', state: 'Tamil Nadu', pincode: '600100', lat: 12.9377, lon: 80.2016, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 220000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Perumbakkam', area: 'Perumbakkam', city: 'Chennai', state: 'Tamil Nadu', pincode: '600100', lat: 12.9213, lon: 80.2100, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 190000, facilities: ['Smart Classrooms', 'Library', 'Music Room'], daycare: true },
    { name: 'Orchids The International School, Pulianthope', area: 'Pulianthope', city: 'Chennai', state: 'Tamil Nadu', pincode: '600012', lat: 13.1064, lon: 80.2642, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 250000, facilities: ['Robotics Lab', 'Auditorium', 'Playground', 'Library'], daycare: false },
    { name: 'Orchids The International School, Thoraipakkam', area: 'Thoraipakkam', city: 'Chennai', state: 'Tamil Nadu', pincode: '600097', lat: 12.9511, lon: 80.2411, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 215000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Art Studio', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Velachery', area: 'Velachery', city: 'Chennai', state: 'Tamil Nadu', pincode: '600042', lat: 12.9785, lon: 80.2185, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 230000, facilities: ['Smart Classrooms', 'Swimming Pool', 'Transportation', 'Cafeteria'], daycare: true },

    // Kolkata
    { name: 'Orchids The International School, Joka', area: 'Joka', city: 'Kolkata', state: 'West Bengal', pincode: '700104', lat: 22.4633, lon: 88.3048, board: 'ICSE', grades: 'Nursery - Grade 12', yearlyFee: 240000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Madhyamgram', area: 'Madhyamgram', city: 'Kolkata', state: 'West Bengal', pincode: '700129', lat: 22.7001, lon: 88.4511, board: 'ICSE', grades: 'Nursery - Grade 10', yearlyFee: 200000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: 'Orchids The International School, Newtown', area: 'Newtown', city: 'Kolkata', state: 'West Bengal', pincode: '700156', lat: 22.5726, lon: 88.4339, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 290000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Auditorium', 'Library', 'Cafeteria'], daycare: true },

    // Gurgaon
    { name: 'Orchids The International School, Dwarka Expressway, Sector 113', area: 'Dwarka Expressway, Sector 113', city: 'Gurgaon', state: 'Haryana', pincode: '122017', lat: 28.5282, lon: 77.0180, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 300000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Golf Course Road', area: 'Golf Course Road', city: 'Gurgaon', state: 'Haryana', pincode: '122002', lat: 28.4566, lon: 77.0917, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 350000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria', 'Smart Classrooms'], daycare: false },
    { name: 'Orchids The International School, Sector 56', area: 'Sector 56', city: 'Gurgaon', state: 'Haryana', pincode: '122011', lat: 28.4217, lon: 77.0911, board: 'ICSE', grades: 'Nursery - Grade 12', yearlyFee: 320000, facilities: ['Swimming Pool', 'Robotics Lab', 'Smart Classrooms', 'Transportation'], daycare: false },
    { name: 'Orchids The International School, South City 1', area: 'South City 1', city: 'Gurgaon', state: 'Haryana', pincode: '122001', lat: 28.4485, lon: 77.0628, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 340000, facilities: ['Auditorium', 'Library', 'Music Room', 'Robotics Lab', 'Smart Classrooms'], daycare: true },

    // Indore
    { name: 'Orchids The International School, Aurobindo Square', area: 'Aurobindo Square', city: 'Indore', state: 'Madhya Pradesh', pincode: '452010', lat: 22.7533, lon: 75.8937, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Rajendra Nagar', area: 'Rajendra Nagar', city: 'Indore', state: 'Madhya Pradesh', pincode: '452012', lat: 22.6844, lon: 75.8306, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 150000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },

    // Sonipat
    { name: 'Orchids The International School, New Braham Colony', area: 'New Braham Colony', city: 'Sonipat', state: 'Haryana', pincode: '131001', lat: 28.9956, lon: 77.0184, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 160000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: 'Orchids The International School, Bahalgarh', area: 'Bahalgarh', city: 'Sonipat', state: 'Haryana', pincode: '131021', lat: 29.0700, lon: 77.0378, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 170000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria'], daycare: false },

    // Delhi
    { name: 'Orchids The International School, Dwarka Sector-19', area: 'Dwarka Sector-19', city: 'Delhi', state: 'Delhi', pincode: '110075', lat: 28.5835, lon: 77.0505, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 280000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Chh Sambhabji Nagar
    { name: 'Orchids The International School, TCH Adgaon', area: 'TCH Adgaon', city: 'Chh Sambhabji Nagar', state: 'Maharashtra', pincode: '422003', lat: 20.0266, lon: 73.8229, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 190000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true }, // Note: Chh Sambhabji Nagar is Nashik

    // Ahmednagar
    { name: 'Orchids The International School, Dhangarwadi', area: 'Dhangarwadi', city: 'Ahmednagar', state: 'Maharashtra', pincode: '414005', lat: 19.1413, lon: 74.7937, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 140000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },

    // Rohtak
    { name: 'Orchids The International School, Gohana Road', area: 'Gohana Road', city: 'Rohtak', state: 'Haryana', pincode: '124001', lat: 28.8551, lon: 76.6213, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 150000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: false },

    // Tumkur
    { name: 'Orchids The International School, SiraGate', area: 'SiraGate', city: 'Tumkur', state: 'Karnataka', pincode: '572106', lat: 13.3618, lon: 77.0945, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 130000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Nagpur
    { name: 'Orchids The International School, Koradi Road', area: 'Koradi Road', city: 'Nagpur', state: 'Maharashtra', pincode: '441111', lat: 21.2290, lon: 79.0911, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 170000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Bhopal
    { name: 'Orchids The International School, Hoshangabad Road', area: 'Hoshangabad Road', city: 'Bhopal', state: 'Madhya Pradesh', pincode: '462026', lat: 23.1815, lon: 77.4419, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 160000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria'], daycare: false },

    // Jabalpur
    { name: 'Orchids The International School, Bhedaghat Road', area: 'Bhedaghat Road', city: 'Jabalpur', state: 'Madhya Pradesh', pincode: '482003', lat: 23.1367, lon: 79.8248, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 150000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Jodhpur
    { name: "Orchids The International School, Saran Nagar", area: "Saran Nagar", city: "Jodhpur", state: "Rajasthan", pincode: "342027", lat: 26.3150, lon: 73.0980, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 140000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: "Orchids The International School, CHB", area: "CHB", city: "Jodhpur", state: "Rajasthan", pincode: "342008", lat: 26.2550, lon: 72.9800, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 160000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: false },
    { name: "Orchids The International School, Banar/CANTT", area: "Banar/CANTT", city: "Jodhpur", state: "Rajasthan", pincode: "342027", lat: 26.3150, lon: 73.0980, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 150000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria'], daycare: true },
    { name: "Orchids The International School, Kudi", area: "Kudi", city: "Jodhpur", state: "Rajasthan", pincode: "342005", lat: 26.2160, lon: 72.9750, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 130000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: "Orchids The International School, Shastri Nagar", area: "Shastri Nagar", city: "Jodhpur", state: "Rajasthan", pincode: "342003", lat: 26.2790, lon: 73.0010, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 200000, facilities: ['Auditorium', 'Library', 'Music Room', 'Robotics Lab'], daycare: false },
    { name: "Orchids The International School, PAL", area: "PAL", city: "Jodhpur", state: "Rajasthan", pincode: "342008", lat: 26.2480, lon: 72.9900, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 170000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Jaipur
    { name: "Orchids The International School, Nevta", area: "Nevta", city: "Jaipur", state: "Rajasthan", pincode: "302029", lat: 26.8125, lon: 75.6980, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 180000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },
    { name: "Orchids The International School, Mahaveer Nagar", area: "Mahaveer Nagar", city: "Jaipur", state: "Rajasthan", pincode: "302018", lat: 26.8523, lon: 75.7925, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 160000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: "Orchids The International School, Pratap Nagar", area: "Pratap Nagar", city: "Jaipur", state: "Rajasthan", pincode: "302033", lat: 26.8078, lon: 75.8450, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 220000, facilities: ['Swimming Pool', 'Auditorium', 'Library', 'Cafeteria'], daycare: false },
    { name: "Orchids The International School, Bhankrota", area: "Bhankrota", city: "Jaipur", state: "Rajasthan", pincode: "302026", lat: 26.8570, lon: 75.6950, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 190000, facilities: ['Smart Classrooms', 'Robotics Lab', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Hubli-Dharwad
    { name: 'Orchids The International School, Charantimath Gardens', area: 'Charantimath Gardens', city: 'Hubli-Dharwad', state: 'Karnataka', pincode: '580024', lat: 15.3647, lon: 75.1239, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 140000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: true },

    // Delhi NCR
    { name: 'Orchids The International School, Delhi NCR (Sonipat)', area: 'Delhi NCR (Sonipat)', city: 'Sonipat', state: 'Haryana', pincode: '131001', lat: 28.9956, lon: 77.0184, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 170000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Cafeteria'], daycare: true },

    // Bangalore
    { name: 'Orchids The International School, Kanakapura Road (Residential)', area: 'Kanakapura Road (Residential)', city: 'Bengaluru', state: 'Karnataka', pincode: '560082', lat: 12.8228, lon: 77.5186, board: 'CBSE', grades: 'Grade 5 - Grade 12', yearlyFee: 450000, facilities: ['Hostel', 'Smart Classrooms', 'Swimming Pool', 'Robotics Lab', 'Auditorium', 'Playground', 'Library', 'Transportation', 'Cafeteria'], daycare: false },

    // Pali
    { name: "Orchids The International School, NHB", area: "NHB", city: "Pali", state: "Rajasthan", pincode: "306401", lat: 25.7950, lon: 73.3450, board: 'CBSE', grades: 'Nursery - Grade 10', yearlyFee: 120000, facilities: ['Smart Classrooms', 'Playground', 'Library'], daycare: true },
    { name: "Orchids The International School, Naya Gaon", area: "Naya Gaon", city: "Pali", state: "Rajasthan", pincode: "306401", lat: 25.7950, lon: 73.3450, board: 'CBSE', grades: 'Nursery - Grade 12', yearlyFee: 130000, facilities: ['Smart Classrooms', 'Playground', 'Library', 'Transportation'], daycare: false }
];
